doma.dialect: h2

zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://localhost:9999
    user-service:
      path: /user/**
      url: http://localhost:8181/me
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/uaa/oauth/token
      userAuthorizationUri: http://localhost:8080/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:8181/me
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
