zuul:
  ignored-services: '*'
  routes:
    user-service: /user/**
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/me
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
